### ISSUE TITLE
BlockingResponse should be an optional return value from webRequest callback

### ISSUE THREAD

**Issue by amiram** [Lusito/webextension-polyfill-ts#10]
According to docs:

> If the optional opt_extraInfoSpec array contains the string 'blocking' (only allowed for specific events), the callback function is handled synchronously. That means that the request is blocked until the callback function returns. In this case, the callback can return a webRequest.BlockingResponse that determines the further life cycle of the request. Depending on the context, this response allows cancelling or redirecting a request (onBeforeRequest), cancelling a request or modifying headers (onBeforeSendHeaders, onHeadersReceived), and cancelling a request or providing authentication credentials (onAuthRequired).

According to this, in onBeforeRequest, onBeforeSendHeaders, onHeadersReceived and onAuthRequired, you can return a BlockingResponse from the callback. Currently it is used only in onAuthRequired but in the async way - an additional callback as a second param of the main callback.
It should be in all 4 events as an optional return param. For example the onBeforeRequest should be:
```
export interface onBeforeRequestEvent extends Events.Event<(details: OnBeforeRequestDetailsType) => BlockingResponse | void> {
        /**
         * Registers an event listener <em>callback</em> to an event.
         *
         * @param callback Called when an event occurs. The parameters of this function depend on the type of event.
         * @param filter Optional. A set of filters that restricts the events that will be sent to this listener.
         * @param extraInfoSpec Optional. Array of extra information that should be passed to the listener function.
         */
        addListener(callback: (details: OnBeforeRequestDetailsType) => BlockingResponse | void, filter?: RequestFilter, extraInfoSpec?: OnBeforeRequestOptions[]): void;
    }
```

**Comment by Lusito** [comment]
I just released a new version to fix these issues.
