### ISSUE TITLE
Can I define custom schemas in addition to the official declarative schemas？

### ISSUE THREAD

**Issue by web-dahuyou** [Lusito/webextension-polyfill-ts#103]
Since the official declarative schemas does not include a tabGroups.json, but i develop a browser extension will use the browser.tabGroups API.

I want to add a tabGroups.json file in the schemas directory by myself, but when I run the npm run fetch command, the tagGroups.json file will be removed.

I am trying to contribute to the tabGroups API, but the code cannot be submitted at the moment.

**Comment by Lusito** [comment]
Currently not. But I don't mind adding it via your PR. So feel free to close this once the PR is merged.
