### ISSUE TITLE
Upgrade to webextension-polyfill version 0.3.0

### ISSUE THREAD

**Issue by theBrianCui** [Lusito/webextension-polyfill-ts#12]
A [new version 0.3.0 of webextension-polyfill](https://github.com/mozilla/webextension-polyfill/releases) was released on July 12, which includes some useful bugfixes and improvements.

It looks like the current version in this repository is 0.2.1. Can we get this updated to 0.3.0?

BTW, huge fan of this project. Thanks for all your hard work so far.

**Comment by Lusito** [comment]
Thanks for the report. I updated it and also updated the schema files (and the generated API) while I was at it.

I'm wondering tho, if I should ditch the dependency to webextension-polyfill alltogether and generate the code myself.
At least what they do in the [api-metadata.json](https://github.com/mozilla/webextension-polyfill/blob/master/api-metadata.json) file seems like it could be generated automatically based on the schema files.

I'll look into this once I have a bit more free time at hand.
