### ISSUE TITLE
Search API has wrong return types

### ISSUE THREAD

**Issue by Dathix** [Lusito/webextension-polyfill-ts#14]
Both functions are returning `void` instead of a Promise.

**Comment by Lusito** [comment]
Sorry, I missed this issue somehow. I can see that the search api has a promise for the get, but the documentation says nothing about the search function:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search/search

Are you sure it returns a promise?

**Comment by Lusito** [comment]
search.get has been fixed. Unless someone tells me the search api has a promise as well, this is closed.
