### ISSUE TITLE
 menus.OnClickData.frameId not modeled

### ISSUE THREAD

**Issue by TheRealMarnes** [Lusito/webextension-polyfill-ts#16]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData

The frameId property is not registered in the model:
![image](https://user-images.githubusercontent.com/3950300/54868310-804f8a00-4d8b-11e9-8dfc-da6f29a0bdde.png)

Adding an `any` cast allows me to access the property anyway:
![image](https://user-images.githubusercontent.com/3950300/54868321-96f5e100-4d8b-11e9-836f-52425172d73e.png)

The property exists at runtime in chrome (where I originally wrote this addon) and firefox:
![image](https://user-images.githubusercontent.com/3950300/54868360-f94ee180-4d8b-11e9-9cf1-54e3d2e1d2cd.png)

Please add the definition :)

**Comment by Lusito** [comment]
Thanks for the report. Will be fixed in the next version.

**Comment by TheRealMarnes** [comment]
Awesome, thanks for the quick fix

**Comment by Lusito** [comment]
Next version has just been released.
