### ISSUE TITLE
'locked' missing from Idle.IdleState

### ISSUE THREAD

**Issue by dkthehuman** [Lusito/webextension-polyfill-ts#23]
`locked` is missing from Idle.IdleState

Code: https://github.com/Lusito/webextension-polyfill-ts/blob/00eb9908031514304366f3f33e0550c52ef5f4bb/src/generated/idle.ts#L16

MDN Docs: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/idle/IdleState

**Comment by Lusito** [comment]
Thanks. Added to the growing list of fixes for mozillas incomplete schema files.
