### ISSUE TITLE
Property 'onSelectionChanged' does not exist on type 'ElementsPanel'

### ISSUE THREAD

**Issue by mantou132** [Lusito/webextension-polyfill-ts#24]
<img width="1010" alt="Screen Shot 2020-03-25 at 23 06 26" src="https://user-images.githubusercontent.com/3841872/77551430-4b6d9a00-6eed-11ea-8ed0-0545a367aa52.png">

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/elements

**Comment by Lusito** [comment]
Thanks for the report!

**Comment by Lusito** [comment]
0.14.0 has been released to fix this.
