### ISSUE TITLE
focused of CreateCreateDataType is nothing

### ISSUE THREAD

**Issue by goroya** [Lusito/webextension-polyfill-ts#25]
I checked  interface CreateCreateDataType.  
But `focused` parameter of browser.windows.create().
Please add it.

※ Please check official document.  
  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create

**Comment by Lusito** [comment]
Thanks. v0.16.0 is released with this fixed.
