### ISSUE TITLE
webRequest.on<Event>.addListener not support async callback

### ISSUE THREAD

**Issue by mantou132** [Lusito/webextension-polyfill-ts#27]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest#addListener_syntax

**Comment by Lusito** [comment]
Thanks for the report. As far as I can tell, this is only for the webRequest events, which can return a BlockingResponse:

- onBeforeRequest
- onBeforeSendHeaders
- onAuthRequired
- onHeadersReceived

I will check how I can work around the incorrect schema files.

**Comment by Lusito** [comment]
Fixed and released
