### ISSUE TITLE
Many errors about modules

### ISSUE THREAD

**Issue by virmundi** [Lusito/webextension-polyfill-ts#3]
When npm builds with webpack I get errors like this.

ERROR in [at-loader] ./node_modules/webextension-polyfill-ts/src/generated/windows.ts:13:24 
    TS2307: Cannot find module './Events'.

Everything seems to work, but it makes it hard to know if there is a real problem without executing the code.

**Comment by Lusito** [comment]
Thanks for the report and the PR.
I'm guessing you're running linux or mac, where case sensitivity is of importance.
I've done my development on windows, which is why I never noticed.
I will check your pull request at the weekend once I have the time.

**Comment by Lusito** [comment]
Merged your PR, but had to rename the method to avoid confusion and removed the console.log messages.
Thanks!
