### ISSUE TITLE
browser.runtime.onMessage.addListener parameters signature incorrect

### ISSUE THREAD

**Issue by mantou132** [Lusito/webextension-polyfill-ts#31]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#Parameters

**Comment by Lusito** [comment]
sendResponse is not part of the signature, because of this part:

> Returning a Promise is now preferred, as sendResponse() will be removed from the W3C spec.

Does the promise version not work for you?

**Comment by mantou132** [comment]
The promise is good, I forgot.
