### ISSUE TITLE
Error when using browser.storage.sync.get

### ISSUE THREAD

**Issue by dkthehuman** [Lusito/webextension-polyfill-ts#32]
In 07e66ea8512b608a, the return type for `browser.storage.sync.get` was changed to `Promise<StorageAreaSyncGetCallbackItemsType>`.

The following line now results in an error:
```typescript
const { [key]: value } = await browser.storage.sync.get(key);
```

Error:
`Type 'StorageAreaSyncGetCallbackItemsType' has no matching index signature for type 'string'.`

Is there a reason the return type was changed from `Promise<{[s:string] : any}>`?

**Comment by Lusito** [comment]
Thanks for the report. Looks like the schemas have changed in a way that I haven't accounted for yet. I'll see what I can do about it.

**Comment by Lusito** [comment]
Correction: Mozilla just duplicated the schema that I already patched. Need to patch the new definition as well. Cleaned a few more things in the process. version 0.19.0 is just released

**Comment by dkthehuman** [comment]
Thanks @Lusito! 🙏🏽
