### ISSUE TITLE
Consulting

### ISSUE THREAD

**Issue by davestewart** [Lusito/webextension-polyfill-ts#36]
Hey @Lusito ...

I wondered, are you available for any consulting?

**Comment by Lusito** [comment]
@davestewart Sorry for the late reply.

Not sure what you mean by consulting.. if you have questions, feel free to ask them. If you want to hire me, I'd have to check with my employer first for legal reasons and it would also depend on the amount of time.

**Comment by davestewart** [comment]
Hey, no worries! We all have lives away from GitHub :P 

I'm right at the tail end of being about to release a project, but have some areas where I think I need external input.

Yes, questions, but suspect they will end up lading to other places, such as sharing code, perhaps some pair programming, etc. I feel that would be outside the realm of OSS goodwill and think it would be more respectful of your time and skills to make it a formal arrangement.  I don't think it's something that would be in conflict with your employment.

Perhaps sending me a DM Twitter and taking it from there would be a good next step?

**Comment by Lusito** [comment]
I don't have Twitter yet. Not sure If I want to either. Reddit, LinkedIn or discourse.mozilla.org maybe? Otherwise good old E-Mail is also possible.

**Comment by davestewart** [comment]
Don't want to put my email publicly, so here's my reddit: https://www.reddit.com/user/dave__stewart

We can go from there :)

**Comment by Lusito** [comment]
contacted you on reddit. Closing this now.
