### ISSUE TITLE
browser.devtools.panels.elements.createSidebarPane('Gem') return undefined

### ISSUE THREAD

**Issue by mantou132** [Lusito/webextension-polyfill-ts#39]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/ElementsPanel/createSidebarPane

**Comment by Lusito** [comment]
This project only adds type definitions to https://github.com/mozilla/webextension-polyfill. If that function returns undefined and should return a promise, you should probably report the bug there. One exception: If you're encountering this in Firefox, the issue should be reported to https://bugzilla.mozilla.org/
