### ISSUE TITLE
Cannot find browser.runtime.requestUpdateCheck() function in webextension-polyfill-ts

### ISSUE THREAD

**Issue by eric2788** [Lusito/webextension-polyfill-ts#44]
![Image](https://user-images.githubusercontent.com/6276840/103334690-4efe0500-4aad-11eb-9021-6749f9f207b9.png)

I am finding a solution to have version checking on chrome / edge but just found the function didn't exist in webextension-polyfill-ts
Is it just what I miss something up, or it should not be existed with reason ?

**Comment by eric2788** [comment]
My temporary solution:
```ts
type UpdateCheck = { requestUpdateCheck: () => Promise<[status: string, update: {version: string}]>}

const forceCheckFunction: Runtime.Static & UpdateCheck = browser.runtime as any
const [status, update] = await forceCheckFunction.requestUpdateCheck()

```

**Comment by Lusito** [comment]
Fixed in latest version. Thanks for the report.
