### ISSUE TITLE
WebRequest.OnBeforeRedirectDetailsType missing Chrome's «initiator» field

### ISSUE THREAD

**Issue by iffjey** [Lusito/webextension-polyfill-ts#47]
It seems like there are differences between Chrome and Firefox WebRequest API concerning WebRequest.OnBeforeRedirectDetailsType

Here's [Firefox MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRedirect#details) version with **originUrl** field

Here's [Chrome](https://developer.chrome.com/docs/extensions/reference/webRequest/#type-OnBeforeRedirectOptions) version with **initiator** field. Also [@types/chrome](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a069b39865132e501f20587af39ba99c1ca596e6/types/chrome-apps/index.d.ts#L12874)

I believe it is the same field with different aliases. Should we add optional **initiator** field to OnBeforeRedirectDetailsType?

**Comment by Lusito** [comment]
Added the initiator field for:
- onAuthRequired
- onBeforeRedirect
- onBeforeRequest
- onBeforeSendHeaders
- onCompleted
- onErrorOccurred
- onHeadersReceived
- onSendHeaders
- onResponseStarted
