### ISSUE TITLE
Project don't work with chrome's new Manifest v3, can be easily fixed

### ISSUE THREAD

**Issue by cattermo** [Lusito/webextension-polyfill-ts#48]
In manifest v3 background workers are run as service workers. This means they don't have access to `window`.  https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#service-workers

The if-statement checking if window is present ruins it for the background script
```
// if not in a browser, assume we're in a test, return a dummy
if (typeof window === "undefined") exports.browser = {};
else exports.browser = require("webextension-polyfill");
```

If I just remove the if-else this library seems to be working fine for Manifest V3.

🙏 Please remove it, for testing jsdom can be used to fake window/document stuff...

**Comment by Lusito** [comment]
Fixed in latest version. Thanks for the report.

**Comment by RanjeetEppa18** [comment]
Does this support updated chrome APIs? e.g `chrome.action`

**Comment by Lusito** [comment]
@AhsanAyaz Since then we have moved to `@types/webextension-polyfill`, so this package no longer provides any code.

If you have switched to `@types/webextension-polyfill`, the only place this might be caused is in the actual code repo: https://github.com/mozilla/webextension-polyfill.
