### ISSUE TITLE
CreateNotificationOptions is missing the buttons field

### ISSUE THREAD

**Issue by conorgil** [Lusito/webextension-polyfill-ts#5]
[interface CreateNotificationOptions](https://github.com/Lusito/webextension-polyfill-ts/blob/master/src/generated/notifications.ts#L32) appears to have all fields in the [Chrome docs](https://developer.chrome.com/extensions/notifications#type-NotificationOptions), except for the `buttons` field.

I haven't figured out how this project works yet, so I am filing this before I forget. Tips on how I can fix this and open a PR are appreciated.

Thanks for your work on this project!

**Comment by Lusito** [comment]
Glad you like it! buttons is currently flagged unsupported in the schema json files of mozilla (and MDN says it's [not supported](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions) as well).
I'm not sure how I want to handle unsupported items yet. Currently, these unsupported items are ignored in the code generation.

In this case, if someone specified buttons, the call would cause an error to be thrown.

I'm open to ideas.

**Comment by conorgil** [comment]
Huh.... look at that. The [MDN docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions) list it in the body of their article, but then say its not supported in the browser compatibility table at the bottom. That certainly is confusing.

Actually, the compat table says that basically nothing is supported in FF for notifications API. However, many of the fields are marked with an `*`, which means that putting the field in there won't throw an error, but it will be ignored. The `buttons` field does not have an `*` and is just marked as unsupported. When testing, the notification doesn't even pop when I include the buttons field. Wompity womp.

Well, it appears there is nothing to do here and you had it right all along. Sorry for the red herring.

**Comment by Lusito** [comment]
There might be different use-cases here.. so if you where to create an extension that uses some features if they are available and others if not, then it would be a valid use-case. There would have to be some checks in place tho. Maybe together with #2, code could be generated to do check for these features. Like: if (browserSupport.notifications.NotificationOptions.buttons) ...

**Comment by conorgil** [comment]
Yea, I have been thinking about going that route because the buttons UX is much nicer than the alternatives that I am coming up with. However, there is certainly a huge tradeoff in terms of maintainability and testing once I start having non-homogeneous features. For now, I am going to stick to features that are supported in both FF and Chrome.

I can see the benefit of exposing the compat data (#2) to make feature toggle decisions, but personally I'm going to avoid that for now. Just letting you know where I'm at so that you don't invest time in a feature unless the community will actually put it to use quickly.

Thanks for brainstorming solutions! Feel free to close this issue out if you think this thread has run its course.
