### ISSUE TITLE
onMessageExternal for external webpage

### ISSUE THREAD

**Issue by OverLord561** [Lusito/webextension-polyfill-ts#52]
The problem is that i am not able to work with external webpages: how to execute callback `sendResponse?`
[https://developer.chrome.com/docs/extensions/mv2/messaging/#external-webpage](url)
This signature is nice to have
`onMessageExternal: Events.Event<(message: any | undefined, sender: MessageSender, sendResponse: Function) => Promise<any> | void>;`
but only this one is present
`onMessageExternal: Events.Event<(message: any | undefined, sender: MessageSender) => Promise<any> | void>;`

**Comment by Lusito** [comment]
Sorry about the delay, this issue slipped through the cracks.

Instead of using sendResponse, please just use the promise return value to send a response. This is the new way of sending a response.
