### ISSUE TITLE
browser.runtime.onMessage.addListener only accepts 2 arguments

### ISSUE THREAD

**Issue by eugbyte** [Lusito/webextension-polyfill-ts#54]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage

The actual `browser.runtime.onMessage.addListener ` accepts 3 arguments:, message, sender, sendResponse. However, the current implementation only accepts 2 arguments: message, sender

**Comment by eugbyte** [comment]
created pull request here:
https://github.com/Lusito/webextension-polyfill-ts/pull/55

**Comment by brnbs** [comment]
Please merge this ASAP

**Comment by Lusito** [comment]
As you can see in the page you linked: "Returning a Promise is now preferred, as sendResponse() will be removed from the W3C spec."

Please use a promise as return value instead of using sendResponse.

I'm going to keep this open, as this pops up regularly, as people don't seem to search before opening new tickets: #53, #46, #45, #31, #7

**Comment by brnbs** [comment]
I landed here from Chrome Developer website where I found no mention about returning a Promise, however I gave it a try and just wanted to confirm that this works the same as calling `sendResponse`:
```
browser.runtime.onMessage.addListener((message: string) => {
    if (message == "whatever") {
        // Do something
        return Promise.resolve("response");
    }
});
```

**Comment by Lusito** [comment]
Chrome documentation is not about the W3C standard. They don't care about the standard at all. If you try to target multiple browsers, I suggest you use the [MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions). Of course, there will be things you need to check if you want chrome-only features and for that you'll need to use the chrome documentation.

**Comment by linonetwo** [comment]
This makes it not easy to pass Observable from backgroundScript to contentScript, an Observable need to send multiple times, after subscribe.

I need something like

```ts
    const ovserver = {
      next: (value) => sender.send(subscriptionId, { type: ResponseType.Next, value }),
      error: (error: Error) => sender.send(subscriptionId, { type: ResponseType.Error, error: Errio.stringify(error) }),
      complete: () => sender.send(subscriptionId, { type: ResponseType.Complete }),
    };
```

To achieve something like https://github.com/frankwallis/electron-ipc-proxy

**Comment by fregante** [comment]
That's now how `sendResponse` works.

If the function is called, then `chrome.runtime.sendMessage` will wait before calling its callback (or in promise-land, before resolving its Promise)

If you call `sendReponse` multiple times, all calls past the first one will just be ignored. There's no such `sender.send` function

**Comment by joshsmith** [comment]
As seen in https://github.com/mozilla/webextension-polyfill/issues/386#issue-1282698182 `sendResponse` should now be supported by this package.

See also updated MDN documentation: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage

**Comment by lhk** [comment]
@Lusito I think the post from joshsmith is important, wouldn't it make sense to update the specification?

**Comment by Lusito** [comment]
Will be fixed in the next version.

For the record: I don't think it's a good idea, because people easily misunderstand this and think they can call it multiple times.
