### ISSUE TITLE
`ExtensionSidebarPane.setObject` accepts a serializable object, not just a string

### ISSUE THREAD

**Issue by fregante** [Lusito/webextension-polyfill-ts#60]
https://github.com/Lusito/webextension-polyfill-ts/blob/8f83cd05ad8b613680c673d64927a250436b00e2/lib/devtools_panels.d.ts#L74-L81

Docs: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels/ExtensionSidebarPane/setObject

> ```js
> var setting = browser.devtools.panels.setObject(
>   jsonObject,       // string, array, or JSON object
>   rootTitle         // string
> )
> ```

**Comment by Lusito** [comment]
Thanks for the report. Fixed in 0.26.0.

**Comment by fregante** [comment]
Thank you!
