### ISSUE TITLE
Investigage contributing to DefinitelyTyped

### ISSUE THREAD

**Issue by Lusito** [Lusito/webextension-polyfill-ts#63]
Might be a good idea to try this:
https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

Things to consider:
- It should still work with mockzilla-webextensions
- Switching to the @types way should be straight forward without too much work.

**Comment by Lusito** [comment]
A PR is on the way: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54471

**Comment by Lusito** [comment]
@fregante The PR has been merged to DT, so the first version of `@types/webextension-polyfill` should be available soon. Feel free to give it a try.

**Comment by Lusito** [comment]
Here it is: https://www.npmjs.com/package/@types/webextension-polyfill

**Comment by fregante** [comment]
Awesome! I'll be testing it at some point. 

Do you plan on moving away from the `webextension-polyfill-ts` package since now `import browser from 'webextension-polyfill'` will use the `@types` package automatically (or TypeScript will prompt to download it)?

**Comment by Lusito** [comment]
If everything works out as expected, I will keep this repository to maintain the code generator, but the npm package `webextension-polyfill-ts` will be deprecated.

But first I want to be sure that everything works fine for all scenarios. I will port my extensions and also https://github.com/Lusito/mockzilla-webextension to use the `@types` version. Before these tasks are complete, this ticket remains open. No promise when I'll get to the tasks though.

**Comment by Lusito** [comment]
Oh, and first I'll need to write a migration guide as well. And after the tasks are complete, I should also make a PR to adjust the  webextension-polyfill readme file (the one by mozilla).

**Comment by fregante** [comment]
Excellent! I think the migration will look something like this?

```diff
- import {browser, Permissions} from 'webextension-polyfill-ts'
+ import browser, {Permissions} from 'webextension-polyfill'
```

Or how I generally use `@types/chrome`:

```diff
- import {browser, Permissions} from 'webextension-polyfill-ts'
+ import browser from 'webextension-polyfill'
+ // const list: browser.Permissions = {/**/}
```

**Comment by Lusito** [comment]
The first one is correct for migrating from webextension-polyfill-ts.

Not sure how you used `@types/chrome` before, but this is how you would then declare a constant with the type of Permissions:

```typescript
import browser, { Permissions } from "webextension-polyfill";
const list: Permissions.Permissions = {};
```
Why write Permissions twice? One is the Namespace and one is the Interface itself.

**Comment by fregante** [comment]
Yeah, what I meant to focus on was avoiding the explicit namespace import because they're (maybe) available on `browser` itself.

Example: (ignore the fact that `browser` is a global)

https://github.com/sindresorhus/refined-github/blob/afa8da1a27e80f6364a3e68ab4b4c5a7c1916d2e/source/background.ts#L12

**Comment by Lusito** [comment]
Yeah, I understand what you're getting at. Didn't have the time to try that.

Feel free to find a way to add this as a feature to the [definitely-typed branch](https://github.com/Lusito/webextension-polyfill-ts/tree/definitely-typed)

**Comment by fregante** [comment]
Haven't tested the new package yet, but it does work on the old one:

<img width="466" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/126060607-7b2bc8d6-9603-4b18-80c4-b045d8a1470e.png">

**Comment by Lusito** [comment]
All done as far as I can see

**Comment by fregante** [comment]
This is great, thanks for the migration guide

**Comment by fregante** [comment]
Do you think it would be possible to also publish these types for the `browser` global to replace the other package and have a single type generator for both?

**Comment by Lusito** [comment]
It is possible, but it's also error-prone, since then those who use it in the import way won't get notified about not importing it and they won't get auto importing via the IDE.

For that use-case, I'd recommend creating a file `global.d.ts` with this content:
```typescript
import type { Browser } from "webextension-polyfill";

declare global {
    const browser: Browser.Browser;
}
```

**Comment by fregante** [comment]
Yes it would have to be its own package in order to avoid that specific situation, but the manual solution also sounds great! It might be worth adding it to the docs

**Comment by Lusito** [comment]
done
