### ISSUE TITLE
`version_name` missing from the manifest

### ISSUE THREAD

**Issue by fregante** [Lusito/webextension-polyfill-ts#68]
Firefox doesn't yet support the key: https://bugzilla.mozilla.org/show_bug.cgi?id=1380219

But it exists: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version_name

```js
browser.runtime.getManifest().version_name
```

**Comment by Lusito** [comment]
Ready when this PR gets merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57314
