### ISSUE TITLE
`onMessage.addListener` does not accept function that returns `true` or `undefined`

### ISSUE THREAD

**Issue by snehalbaghel** [Lusito/webextension-polyfill-ts#69]
As per the notecard on documentation of [onMessage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#parameters) the onMessage listener should return `false` or `undefined` if the listener is not meant to respond to a certain message so it doesn't block other listeners from responding. Doing so throws the following type error:

```
Argument of type '(message: any, sender: MessageSender) => boolean' is not assignable to parameter of type '(message: any, sender: MessageSender) => void | Promise<any>'.
  Type 'boolean' is not assignable to type 'void | Promise<any>'.ts(2345)
```

**Comment by Lusito** [comment]
As said in #54, the old way of using sendResponse is not meant to be used anymore. Return a Promise if you want to send a response. Otherwise don't return anything.

If you suspect I am misunderstanding the issue, please re-open this ticket.

**Comment by snehalbaghel** [comment]
@Lusito The above documentation that I'm referring to applies to promises not `sendResponse`:

![Screenshot 2021-12-17 at 3 05 44 PM](https://user-images.githubusercontent.com/17233313/146523253-ed491298-97d2-4398-9f80-a1ad178fa0d4.png)

**Comment by Lusito** [comment]
The boolean return value is still connected to the sendResponse:
- return true to use sendResponse
- return a promise to use the new method.
- return void/undefined or false to not respond at all.

The example you are showing is a bit misleading. You could just omit the `return false` statement and it should behave the same way.

If you still think there should be a possibility to return a boolean, please give me an example what you want to achieve and then we can try to sort this out.
