### ISSUE TITLE
onMessage sendResponse should get a single param

### ISSUE THREAD

**Issue by amiram** [Lusito/webextension-polyfill-ts#7]
According to docs, the third param of the listener to onMessage should be a function that gets a single param. In here it is defined as a function without params:
`onMessage: Events.Event<(message: any | undefined, sender: MessageSender, sendResponse: () => void) => void>;`

So this code is invalid:
`browser.runtime.onMessage.addListener((message, sender, sendResponse) => {
    sendResponse({result: 1});
});`

This will fix it:
`onMessage: Events.Event<(message: any | undefined, sender: MessageSender, sendResponse: (message: any) => void) => void>;`

**Comment by Lusito** [comment]
Thanks for the report, but sendResponse is going to be removed from the W3C spec, that's why it's like this:

>Returning a Promise is now preferred way as sendResponse will be removed from W3C spec. The popular webextension-polyfill library already removed this function from it's implementation.

See: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessage

**Comment by Lusito** [comment]
Actually, sendResponse shouldn't even be there anymore.. I'l leave this ticket open to remove it from the API.

**Comment by amiram** [comment]
Correct, I just tried it and it is undefined.

**Comment by amiram** [comment]
I see now that the return value from the listener was changed to `boolean | void`. It should be `Promise<any> | boolean | void` because boolean is the old way to keep the connection open and send the response via sendResponse callback asynchronously, but as you wrote above it should be done now with a promise with the result.

**Comment by Lusito** [comment]
fixed. boolean is not valid as a return value anymore either, as it was only used for the sendResponse callback.
