### ISSUE TITLE
`browser.commands.onCommand.addListener`’s handler lacks Tab parameter

### ISSUE THREAD

**Issue by fregante** [Lusito/webextension-polyfill-ts#70]
This package’s commands.d.ts:

```ts
        /**
         * Fired when a registered command is activated using a keyboard shortcut.
         *
         * @param command
         */
        onCommand: Events.Event<(command: string) => void>;
```

`@types/chrome`:

```ts
    export interface CommandEvent extends chrome.events.Event<(command: string, tab: chrome.tabs.Tab) => void> { }
```

In short, something like this should be allowed:

```ts
browser.commands.onCommand.addListener((
  command: string,
  tab: chrome.tabs.Tab
) => {
// etc
});
```

**Comment by Lusito** [comment]
I'll add the parameter. But according to [chrome docs](https://developer.chrome.com/docs/extensions/reference/commands/#event-onCommand), the tab parameter is optional (i.e. it can be undefined). Since Firefox doesn't support it, that would be my preferred value as well.

**Comment by Lusito** [comment]
I've pushed it here:
https://github.com/Lusito/webextension-polyfill-ts/blob/master/out/namespaces/commands.d.ts
Please verify if this is okay for you. I'll create a PR against DT after that.
