### ISSUE TITLE
webRequest addListener filter should be mandatory

### ISSUE THREAD

**Issue by amiram** [Lusito/webextension-polyfill-ts#8]
According to docs of mozilla, filter is mandatory:

> All the events, except onErrorOccurred, can take three arguments to addListener():
- the listener itself
- a filter object, so you can only be notified for requests made to particular URLs or for particular types of resource
- an optional extraInfoSpec object. You can use this to pass additional event-specific instructions.

I tried it myself and I get an error if I don't supply any filter.

**Comment by Lusito** [comment]
This was an ugly workaround to solve inheritance issues with `events.Event`, but I found a nicer way to do this.

**Comment by Lusito** [comment]
new version is released on npm

**Comment by amiram** [comment]
Thanks for the quick fixes! I need to open pull requests next time. This type library is really smart.
