### ISSUE TITLE
Missing members for `browser.webNavigation.onCommitted` details callback argument

### ISSUE THREAD

**Issue by mnoorenberghe** [Lusito/webextension-polyfill-ts#80]
It's in the [Firefox Schema](https://hg.mozilla.org/integration/autoland/file/bffc883660b7784f77ebed127100d4067f8ddcea/toolkit/components/extensions/schemas/web_navigation.json#l191) and [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCommitted) but for some reason the type generation is missing a bunch of members, it only has the following:
```ts
    interface OnCommittedDetailsType {
        /**
         * The ID of the tab in which the navigation occurs.
         */
        tabId: number;

        url: string;

        /**
         * 0 indicates the navigation happens in the tab content window; a positive value indicates navigation in a subframe.
         * Frame IDs are unique within a tab.
         */
        frameId: number;

        /**
         * The time when the navigation was committed, in milliseconds since the epoch.
         */
        timeStamp: number;
    }
```

**Comment by mnoorenberghe** [comment]
Nevermind, I see now that it has `"unsupported": true`

**Comment by mnoorenberghe** [comment]
The incorrect `unsupported:true` were removed in https://bugzilla.mozilla.org/show_bug.cgi?id=1837829

**Comment by Lusito** [comment]
@mnoorenberghe would you mind reviewing this PR? It helps speed up the release:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65870

**Comment by mnoorenberghe** [comment]
Done. Looks like it's ready to merge
