### ISSUE TITLE
[MV3] WebExtensionManifestBackgroundC3Type interface should support type: "module" optional property

### ISSUE THREAD

**Issue by Kilbourne** [Lusito/webextension-polyfill-ts#83]
[https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#man-sw](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#man-sw)
Currently i get _Object literal may only specify known properties, and 'type' does not exist in type WebExtensionManifestBackgroundC3Type_

**Comment by Lusito** [comment]
Thanks for the report, will be fixed with the next version
