### ISSUE TITLE
browser.alarms.get should return `Promise<Alarm | undefined>`

### ISSUE THREAD

**Issue by davidbielik** [Lusito/webextension-polyfill-ts#84]
Current type definition for `browser.alarms.get` return `Promise<Alarm>`

But if you were you get an alarm that does not exist, it returns `undefined`:

```typescript
console.log(await browser.alarms.get("i-dont-exist"));
```

How can we get this type updated (and therefore updated in [`@types/webextension-polyfill`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webextension-polyfill/namespaces/alarms.d.ts) corrected?

**Comment by Lusito** [comment]
Thanks for the report, will be resolved when the next version gets out
