### ISSUE TITLE
storage.StorageArea.onChanged listener parameter should be a Record

### ISSUE THREAD

**Issue by Vinnl** [Lusito/webextension-polyfill-ts#85]
[According to MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/onChanged#addlistener_syntax), the first parameter to the listener

> contains one property for each key that changed. The name of the property is the name of the key that changed, and its value is a [storage.StorageChange](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageChange) object describing the change to that item.

In other words, a `Record<string, StorageChange>`.

However, in the type definitions, it looks like the parameter itself is the `StorageChange` type directly, rather than in a `Record`:

![Autocomplete when accessing the first parameter to `addListener`, showing available properties `oldValue` and `newValue`, which should only be available on nested properties.](https://user-images.githubusercontent.com/4251/209349504-aac97084-63c1-44de-a426-f0e955b8d8d4.png)

Not sure if I should report this in this repo, or if I need to report it somewhere for the upstream schemas - would appreciate pointers if it's the latter.

**Comment by Lusito** [comment]
That looks like incorrect indeed. Thanks for the report.
I am honestly not sure, if this is a problem of the schemas or my misunderstanding of the schemas. I will take a look.

Aside from that: it's really difficult to make changes to the schema files, as you'll have to get into mozillas versioning tools. I've tried a while back and concluded, that I'd rather make fixes here.

**Comment by Lusito** [comment]
It seems it was my misunderstanding of the schemas. Will be fixed in the next version.

**Comment by Vinnl** [comment]
Fantastic, thank you so much!
