### ISSUE TITLE
RequestFilter array property types allowing only one element

### ISSUE THREAD

**Issue by amiram** [Lusito/webextension-polyfill-ts#9]
In RequestFilter there are two properties that supposed to be arrays: urls and types. They are written like this:
```
urls: [string];
types?: [ResourceType];

```
This kind of arrays allows only a single element. The definition of an array should be:
```
urls: string[];
types?: ResourceType[];

```

**Comment by Lusito** [comment]
hmm, good catch.. this actually was working correctly before [TypeScript 2.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html).. they changed how tuples work in that version.

**Comment by Lusito** [comment]
I just released a new version to fix these issues. For now, only arrays with min-length === max-length will be written as [string, ...]. Arrays with a min-length will -for now- be written as normal arrays, as there seems to be no nice way to solve this, but I'll look into this a bit more.

**Comment by amiram** [comment]
Thanks for the quick fix
