### ISSUE TITLE
Tabs.sendMessage is missing callback?: function

### ISSUE THREAD

**Issue by gxy5202** [Lusito/webextension-polyfill-ts#91]
types
![image](https://user-images.githubusercontent.com/37973863/229163964-daf92064-21b5-44f9-81a9-d72fc6a49dbc.png)

chrome's official doc
![image](https://user-images.githubusercontent.com/37973863/229164039-b151b819-6b0e-4ac5-9c7b-5e0e6f643eea.png)

**Comment by Lusito** [comment]
Hi @gxy5202, the normal way to interact with callback-style functions using the webextension-polyfill is to await the promise instead of passing in a callback.

Chrome example:
```ts
chrome.tabs.sendMessage(tabId, message, { frameId }, (response) => {
    handleResponse(response);
});
```

webextension-polyfill async/await example:
```ts
const response = await browser.tabs.sendMessage(tabId, message, { frameId });
handleResponse(response);
```

webextension-polyfill promise example:
```ts
browser.tabs.sendMessage(tabId, message, { frameId }).then((response) => {
    handleResponse(response);
});
```

I hope this helps.

**Comment by gxy5202** [comment]
> Hi @gxy5202, the normal way to interact with callback-style functions using the webextension-polyfill is to await the promise instead of passing in a callback.
> 
> Chrome example:
> 
> ```ts
> chrome.tabs.sendMessage(tabId, message, { frameId }, (response) => {
>     handleResponse(response);
> });
> ```
> 
> webextension-polyfill async/await example:
> 
> ```ts
> const response = await browser.tabs.sendMessage(tabId, message, { frameId });
> handleResponse(response);
> ```
> 
> webextension-polyfill promise example:
> 
> ```ts
> browser.tabs.sendMessage(tabId, message, { frameId }).then((response) => {
>     handleResponse(response);
> });
> ```
> 
> I hope this helps. (Keep in mind, I left out error handling in these examples)

Thanks, this exactly solves my problem but I just wondered, as a polyfill, shouldn't it be compatible with both ways?

**Comment by gxy5202** [comment]
I just noticed that this callback type has been added, but the latest npm package has not been released yet?

**Comment by Lusito** [comment]
> Thanks, this exactly solves my problem but I just wondered, as a polyfill, shouldn't it be compatible with both ways?

It really depends on how you want to define polyfill. Chrome is not making an effort to make webextensions a standard. Mozilla is. If Mozilla is defining the standard, then the polyfill should abstract away differences in browsers, which don't match the standard.

Anyway, as far as I understand the following section, it's not possible to use the callback style with JavaScript:
https://github.com/mozilla/webextension-polyfill#using-the-promise-based-apis

So if you'd really want that possibility, you'd have to take it up with the maintainers of that repo. This one is just for the types. Not sure why anyone would want the callback-style API though, as promise-based is getting more and more standard even outside of webextensions.

> I just noticed that this callback type has been added, but the latest npm package has not been released yet?

Not sure where you see this.. here is the code, that is currently released:
https://github.com/Lusito/webextension-polyfill-ts/blob/6f1b96fc14e6d87830af362ae8939a4207ca5766/out/namespaces/tabs.d.ts#L1063

**Comment by gxy5202** [comment]
> > Thanks, this exactly solves my problem but I just wondered, as a polyfill, shouldn't it be compatible with both ways?
> 
> It really depends on how you want to define polyfill. Chrome is not making an effort to make webextensions a standard. Mozilla is. If Mozilla is defining the standard, then the polyfill should abstract away differences in browsers, which don't match the standard.
> 
> Anyway, as far as I understand the following section, it's not possible to use the callback style with JavaScript:
> https://github.com/mozilla/webextension-polyfill#using-the-promise-based-apis
> 
> So if you'd really want that possibility, you'd have to take it up with the maintainers of that repo. This one is just for the types. Not sure why anyone would want the callback-style API though, as promise-based is getting more and more standard even outside of webextensions.
> 
> > I just noticed that this callback type has been added, but the latest npm package has not been released yet?
> 
> Not sure where you see this.. here is the code, that is currently released:
> https://github.com/Lusito/webextension-polyfill-ts/blob/6f1b96fc14e6d87830af362ae8939a4207ca5766/out/namespaces/tabs.d.ts#L1063

Thanks for your explanation, i totally agree with it. In fact, promise should be the best resolution for javascript and we all should use it to replace the old callback way, i think that's absolutely right. 

On the other hand, we know nodejs also use callback in his api at the first, after he adds promise way, callback way is retained. Maybe it's because of historical issue and for the smooth upgrade. My point is that if a user's extension can not successfully upgrad his old version browser which means developer can not upgrade es5 to es6, i know this is a special case, but is there any possibility   that he doesn't need to change his code style  (such as replace callback function or mv2 to mv3) when he is using this polyfill?

And I see a callback function defined in https://github.com/Lusito/webextension-polyfill-ts/blob/master/schemas/tabs.json, if it's not the right file, please ignore my question.🤣 

Anyway, thanks again for creating this repo to help developers like me.

**Comment by Lusito** [comment]
The schema files are mozillas kind of a blueprint for the webextension api, but they are flawed in many ways. That's why there are so many files in the fixes folder.

I use them to generate the definitions, but there is no good documentation on them. My best guess is, that Mozilla has created them a long time ago, when promises have not been around and they didn't get to rewrite them yet.

When the schema defines `"async": "responseCallback"` or `"async": "callback"` for a function, it actually means, that they are using the promise-style syntax and the last parameter in the list defines what the response type of the promise is.

About node.js: There are a ton of libraries, which build upon node, so it's probably a compatibility thing to keep them around, so that all of these libraries keep working.

> but is there any possibility that he doesn't need to change his code style (such as replacing callback function or mv2 to mv3) when he is using this polyfill?

Well, as said, you'd have to ask that at the polyfill itself: https://github.com/mozilla/webextension-polyfill
If they  make it possible, it can be done in the types as well.

**Comment by gxy5202** [comment]
Thank you, I understand that and I leaned a lot. I will close this issue.
