### ISSUE TITLE
`ExecutionWorld` type is missing `"MAIN"` value in `executeScript`

### ISSUE THREAD

**Issue by davidbielik** [Lusito/webextension-polyfill-ts#92]
Hi there, The `ExecutionWorld` type should also include `"MAIN"`. Can this be added to `@types/webextension-polyfill`?

https://developer.chrome.com/docs/extensions/reference/scripting/#type-ExecutionWorld

```typescript
 await browser.scripting.executeScript({
    target: { tabId },
    // @ts-expect-error @types/webextension-polyfill are wrong
    world: 'MAIN',
    func: function () {}
});

**Comment by Lusito** [comment]
Thanks for the report and sorry for the delay. Somehow this slipped past me. Will be released with the next version
